language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - hhvm-nightly

before_script:
  - php --version
  - composer selfupdate
  - export PHP_CURRENT='5.6'

script:
  - make test
  - if [ $(phpenv version-name) = '5.6' ]; then make test-upload; fi
  - make clean

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm
    - php: hhvm-nightly

notifications:
  webhooks:
    urls:
      - http://derricks.io/repositories/buildhooks/
    on_success: always
    on_failure: always
    on_start: true
